all: ociuldr 

ociuldr: ociuldr.c
	gcc -m32 -g -Bsymbolic -t -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I${ORACLE_HOME}/rdbms/demo -I${ORACLE_HOME}/rdbms/public -L${ORACLE_HOME}/lib32 -Wl,-i -o ociuldr ociuldr.c -lm -lclntsh -Wl,-Bdynamic

clean:
	rm -rf ociuldr

